packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.87.1
  "@trpc/client": ^11.5.1
  "@trpc/server": ^11.5.1
  "@trpc/tanstack-react-query": ^11.5.1
  "@eslint/js": ^9.35.0
  eslint: ^9.35.0
  prettier: ^3.6.2
  tailwindcss: ^4.1.13
  "@tailwindcss/postcss": ^4.1.13
  typescript: ^5.9.2
  zod: ^4.1.5

catalogs:
  react19:
    "@types/react": ^19.1.12
    "@types/react-dom": ^19.1.9
    react: 19.1.1
    react-dom: 19.1.1

onlyBuiltDependencies:
  - esbuild

overrides:
  "@types/minimatch": 5.1.2
  "lightningcss": "1.30.1" # https://github.com/nativewind/nativewind/issues/1605

linkWorkspacePackages: true

# FIXME: https://github.com/prettier/prettier/issues/17565
publicHoistPattern:
  - "@ianvs/prettier-plugin-sort-imports"
  - "prettier-plugin-tailwindcss"
