packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.59.15
  "@trpc/client": &trpcVersion ^11.0.0-rc.601
  "@trpc/react-query": *trpcVersion
  "@trpc/server": *trpcVersion
  eslint: ^9.12.0
  prettier: ^3.3.3
  tailwindcss: ^3.4.14
  typescript: ^5.6.3
  zod: ^3.23.8

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.11
    "@types/react-dom": ^18.3.1
