packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@auth/drizzle-adapter": ^1
  "@hookform/resolvers": ^3
  "@tanstack/react-query": ^5
  "@trpc/client": ^11.0.0-rc.477
  "@trpc/react-query": ^11.0.0-rc.477
  "@trpc/server": ^11.0.0-rc.477
  "@types/react": npm:types-react@rc
  "@types/react-dom": npm:types-react-dom@rc
  "@types/node": ^20
  "@t3-oss/env-nextjs": ^0
  drizzle-kit: ^0
  drizzle-orm: ^0
  eslint: ^9
  "eslint-plugin-jsx-a11y": ^6
  "eslint-plugin-react": ^7
  next: ^15
  next-auth: 5.0.0-beta.20
  next-themes: ^0
  prettier: ^3
  react: rc
  react-dom: rc
  react-hook-form: ^7
  sonner: ^1
  superjson: ^2
  tailwindcss: ^3
  typescript: ^5
  zod: ^3
