packages:
  - apps/*
  - packages/*
  - tooling/*
catalog:
  eslint: ^9.28.0
  prettier: ^3.5.3
  tailwindcss: ^3.4.15
  typescript: ^5.8.3
  zod: ^3.25.49
  "@tanstack/react-query": ^5.80.7
  "@trpc/client": ^11.5.1
  "@trpc/tanstack-react-query": ^11.5.1
  "@trpc/server": ^11.5.1
catalogs:
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": ^19.1.6
    "@types/react-dom": ^19.1.5
onlyBuiltDependencies:
  - esbuild
